# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\python-gui\pyQt5-demo\Weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1159, 762)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 1101, 631))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 40, 72, 15))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(100, 40, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")

        self.comboBox.addItem("")

        self.comboBox.addItem("")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(50, 90, 1011, 511))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.groupBox)
        self.clearBtn = QtWidgets.QPushButton(Dialog)
        self.clearBtn.setGeometry(QtCore.QRect(40, 700, 93, 28))
        self.clearBtn.setObjectName("clearBtn")

        self.queryBtn = QtWidgets.QPushButton(Dialog)
        self.queryBtn.setGeometry(QtCore.QRect(960, 720, 93, 28))
        self.queryBtn.setObjectName("queryBtn")

        self.queryBtn.clicked.connect(Dialog.queryWeather)

        self.clearBtn.clicked.connect(Dialog.clearText)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "城市天气预报查询"))
        self.label.setText(_translate("Dialog", "城市"))
        self.clearBtn.setText(_translate("Dialog", "清空"))
        self.queryBtn.setText(_translate("Dialog", "查询"))
        self.comboBox.setItemText(0, _translate("Dialog", "嘉定区"))
        self.comboBox.setItemText(1, _translate("Dialog", "上海"))
        self.comboBox.setItemText(2, _translate("Dialog", "苏州"))
        self.comboBox.setItemText(3, _translate("Dialog", "北京"))



